apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-companion-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learning-companion-app
  template:
    metadata:
      labels:
        app: learning-companion-app
    spec:
      containers:
      - name: learning-companion-app
        image: pri2103/learningcompanion:v33
        ports:
        - containerPort: 8501
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: groq-api-secret
              key: GROQ_API_KEY