apiVersion: v1
kind: Service
metadata:
  name: learning-companion-service
spec:
  selector:
    app: learning-companion-app
  ports:
    - port: 80
      targetPort: 8501  # default port for Streamlit
  type: NodePort